Add #include command for series and use apply_patch_series rekursiv - do backport latest changes to all old version (down to 2.6.18)

diff --git a/scripts/apply_patch_series b/scripts/apply_patch_series
--- a/scripts/apply_patch_series
+++ b/scripts/apply_patch_series
@@ -13,14 +13,26 @@ series=$1
 shift
 rm -f .patchOK
 while read -r pname popt ; do
-	if [ "${pname:0:1}" != "#" ]; then
-		echo "Apply $pname : opts=$popt"
+	res=0
+	if [ -z "$pname" ]; then
+		echo "Ignore empty line"
+		continue
+	elif [ "${pname:0:1}" != "#" ]; then
+		echo "Apply $pname : opts=$popt from series ${series}"
 		$PATCH -p1 $popt < patches/${pname}
 		res=$?
 		if [ $res -ne 0 ]; then
-			echo "Error on $PATCH -p1 $popt < patches/${pname}"
+			echo "Error on $PATCH -p1 $popt < patches/${pname} in series ${series}"
 			exit 1
-		fi 
+		fi
+	elif [ "${pname}" = "#include" ]; then
+		echo "Include series ${popt}" 
+		../scripts/apply_patch_series ../series/${popt}
+		res=$?
+		if [ $res -ne 0 ]; then
+			exit 1
+		fi
+		rm -f .patchOK
 	fi
 done < <(cat $series)
-echo "All patches OK" >> .patchOK
+echo "All patches OK" > .patchOK
