Check that patches do not fail
Do not use patch -R it is easier to handle the stack of patches with quilt.
Unfortunately quilt refresh does not allow to generate a reversed order patch,
so it is better to not use them.

Signed-off-by: Karsten Keil <keil@b1-systems.de>

diff --git a/scripts/apply_patch_series b/scripts/apply_patch_series
--- a/scripts/apply_patch_series
+++ b/scripts/apply_patch_series
@@ -11,10 +11,16 @@ fi
 
 series=$1
 shift
-
+rm -f .patchOK
 while read -r pname popt ; do
 	if [ "${pname:0:1}" != "#" ]; then
 		echo "Apply $pname : opts=$popt"
 		$PATCH -p1 $popt < patches/${pname}
+		res=$?
+		if [ $res -ne 0 ]; then
+			echo "Error on $PATCH -p1 $popt < patches/${pname}"
+			exit 1
+		fi 
 	fi
 done < <(cat $series)
+echo "All patches OK" >> .patchOK
